/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssociadoRouteImport } from './routes/associado'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LevelsRouteImport } from './routes/levels'
import { Route as MarketRouteImport } from './routes/market'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as WalletRouteImport } from './routes/wallet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssociadoRoute = AssociadoRouteImport.update({
  id: '/associado',
  path: '/associado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsRoute = LevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/associado': typeof AssociadoRoute
  '/auth': typeof AuthRoute
  '/levels': typeof LevelsRoute
  '/market': typeof MarketRoute
  '/parceiros': typeof ParceirosRoute
  '/profile': typeof ProfileRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/associado': typeof AssociadoRoute
  '/auth': typeof AuthRoute
  '/levels': typeof LevelsRoute
  '/market': typeof MarketRoute
  '/parceiros': typeof ParceirosRoute
  '/profile': typeof ProfileRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/associado': typeof AssociadoRoute
  '/auth': typeof AuthRoute
  '/levels': typeof LevelsRoute
  '/market': typeof MarketRoute
  '/parceiros': typeof ParceirosRoute
  '/profile': typeof ProfileRoute
  '/wallet': typeof WalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/admin'
    | '/associado'
    | '/auth'
    | '/levels'
    | '/market'
    | '/parceiros'
    | '/profile'
    | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/admin'
    | '/associado'
    | '/auth'
    | '/levels'
    | '/market'
    | '/parceiros'
    | '/profile'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/admin'
    | '/associado'
    | '/auth'
    | '/levels'
    | '/market'
    | '/parceiros'
    | '/profile'
    | '/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdminRoute: typeof AdminRoute
  AssociadoRoute: typeof AssociadoRoute
  AuthRoute: typeof AuthRoute
  LevelsRoute: typeof LevelsRoute
  MarketRoute: typeof MarketRoute
  ParceirosRoute: typeof ParceirosRoute
  ProfileRoute: typeof ProfileRoute
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/associado': {
      id: '/associado'
      path: '/associado'
      fullPath: '/associado'
      preLoaderRoute: typeof AssociadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels': {
      id: '/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof LevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdminRoute: AdminRoute,
  AssociadoRoute: AssociadoRoute,
  AuthRoute: AuthRoute,
  LevelsRoute: LevelsRoute,
  MarketRoute: MarketRoute,
  ParceirosRoute: ParceirosRoute,
  ProfileRoute: ProfileRoute,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
